### PR TITLE
[ENHANCEMENT] adding the ability to compare JSON.stringify'd data

### PR DESCRIPTION
**Pull request by williamsbdev**
@JarrodCTaylor, we ran into this issue where our real request data and mock data was `JSON.stringify'd` and when we would do the compare, it would fail because the keys were not in the same order.

I added a test to show that keys out of order of a regular object "match" but when `JSON.stringify'd`, they do not.

We initially thought it was in this [library](https://github.com/toranb/ember-cli-test-helpers/issues/19) but upon my further investigation, it is in fact something that we think should be handled here. This is my first stab at the fix for this.
## PLEASE do not merge this as is.

I believe it needs some work to remain consistent with this project's style and I am not proud of the code but it has the passing test so we can refactor to make it what you would find as acceptable.

Thanks!

cc @toranb @benkiefer

### CODE REVIEW

**Comment by toranb** [comment]
Nice work on this PR! It's been near the top of my kill list for some time now!

**Comment by JarrodCTaylor** [comment]
I don't think there is an issue here that needs to be fixed. The request in your second test is not being mocked because the string you are providing to `data` is different. Objects are not ordered so your first test will be successfully mocked because the Objects provided for `data` are actually equal. When you stringify them it would be equivalent to passing the string `"Brandon Williams"` to one and `"Williams Brandon"` to the other those do not match. With `strictMatching` on you are telling fauxjax to not mock the request unless all the data matches.  I don't think fauxjax should be inspecting strings and attempting to infer what it thinks you want to do. By leveraging the `strictMatching` setting you should be able to accomplish your testing goals with the lib the way it is. 

I have slightly modified your second test so it will pass. If you set `strictMatching` to `false` and omit the `data` attribute when creating the fauxjax instance. Fauxjax will not require that the data fields match. It will mock any `POST` to that `url`. 

``` coffeescript
test "When faux and real request have the same data JSON.stringify'd the request is successfully faked", (assert) ->
  done = assert.async()
  $.fauxjax.settings.strictMatching = false
  $.fauxjax.new
    request:
      method: "POST"
      url: "/faux-request"
    response:
      content: {fakeResponse: "Post success"}

  $.ajax
    method: "POST"
    url: "/faux-request"
    data: JSON.stringify({wat: "baz", foo: "bar"})
    success: (data, textStatus, xhr) ->
      assert.ok(true, "Request did not succeed and should have been successfully faked")
      assert.ok(_.isEqual(data, {"fakeResponse": "Post success"}), "Response text not a match received: #{data}")
    error: (xhr, textStatus) ->
      assert.ok(false, "Faux data does match the real request data. The request should not have returned an error")
    complete: (xhr, textStatus) ->
      done()
```

**Comment by williamsbdev** [comment]
@JarrodCTaylor we really want to be able to match our request data/mock data even though it is `JSON.stringify` on the keys and values and not on the literal string. What do you think of giving us a hook to compare the data ourselves? Potentially something that we can override via the settings with our own function.

**Comment by JarrodCTaylor** [comment]
But you are stringifying the Object there are no more keys and values to match it is just a string, and the string doesn't match. If you want keys and values why are you doing a stringify? The current built in functionality allows your example test to pass. I can't see the need of writing hooks to add in alternate compare functions. Why would we only do with with `data` and not `url`, `method` and `headers`? As is you can test what happens with the response from the ajax call which is the intended purpose of the library. If you are unsure about application logic that builds up arguments to post then I would say test that functionality on its own. Unless I am missing something what you are asking for is not what the propose of this lib is.

**Comment by williamsbdev** [comment]
@JarrodCTaylor I would love to know if you are doing a `JSON.stringify` before sending your data to the server? We have to do this otherwise we get invalid json when interacting with the ember-cli server mode. Can you provide me an example of your ajax requests? Do you use the strictMatching?

**Comment by benkiefer** [comment]
Are you sure that you are sending JSON to your server?

There is no way to send JSON without calling JSON.stringify before the send.

**Comment by williamsbdev** [comment]
@JarrodCTaylor with my most recent refactor, I am only doing a `JSON.parse` when the `realRequestContext.contentType === "application/json"`. I think this is more in line with what is actually happening. If it is `"application/json"` the data must be `JSON.stringify'd`. Therefore, it is doing double check that a) it is in fact `JSON.stringify'd` as it will throw an error if it is simple object and b) it will not require us to `JSON.stringify` the mock data and will compare the keys which is the desired outcome. We do not care if the keys are out of order between the two, we just care that they match.

I understand what you are saying that maybe this request is asking the library to do more than it was intended for. In the simplest form, you are absolutely correct, the stringify'd versions do not match. and this library is intended to be a simple way to ensure that requests are mocked and can return some specified response. I have built on top of the primitives that are provided, unfired and unhandled, in a [test done function](https://github.com/toranb/ember-cli-test-helpers/blob/master/test-support/helpers/test-done.js). You were my guide to do it this way.

Thank you for this project and all the work you've done to keep it simple and clean. It has been a joy to use this library.

**Comment by JarrodCTaylor** [comment]
Fine I will scrap the long response and client/server example that I worked up and was getting ready to press comment on :stuck_out_tongue: No need for it now as you have hit on the issue that I was going to illuminate. You had not mentioned that you wanted to change `contentType` and it was not previously reflected in your test so the stringification made no sense to me. By default an ajax `POST` will use `application/x-www-form-urlencoded` which allows you to provide a JS Object as the value for `data`. If your particular use case (sending binary or large amounts of data) requires you to use `application/json` for the `contentType` then yes you will need to stringify the data. Checking for `contentType` is the only thing that makes sense to me for the library. I will review the pull request since it sounds like you have come around to this way of thinking as well.

**Comment by williamsbdev** [comment]
I apologize as my original test case did not have that. Let's continue to work through this PR to make sure that is something we both like and can agree on. I am not set in stone on what is currently there and would your help to continue improving it and make it something that is maintainable.

**Comment by JarrodCTaylor** [comment]
@williamsbdev I think this is the right approach and looks good :thumbsup: 

One very minor enhancement. How about `parseContentType` instead of `convertData`? Since we are for sure examining the content type but not necessarily converting it. Also pull the empty lines out of `shouldMockRequest` and I'll be glad to merge this in. 

Good work.

**Comment by williamsbdev** [comment]
@jarrodctaylor I made the changes above and while I was in there and
cleaning up my documentation, I saw a couple of methods that were missing
some documentation. Let me know if all the changes look good or if you
would like me to revert/modify some.

Thanks!

**Comment by JarrodCTaylor** [comment]
Looks good. Nice work grinding this one out. Thanks. 

I will merge this and then bump the version.

**Pull request merged**
