### PR TITLE
fix backwards compatibility when string are used for mock data and co…

### PR DESCRIPTION
**Pull request by benkiefer**
…ntent type is json

### CODE REVIEW

**Comment by benkiefer** [comment]
fixes #22

**Comment by benkiefer** [comment]
We are not advocating keeping this forever. Maybe remove in a 2.x release?

**Comment by JarrodCTaylor** [comment]
I will look into refactoring specifying contentType this weekend. There shouldn't be any reason to be setting contentType on a GET request. So some of this is moot.

**Comment by benkiefer** [comment]
The contentType has nothing to do with the request being a get. It is entirely possible that there could be a POST with no body if it was triggering a change (ex: triggering the sending of an email).

The correct logic on setting the content type should have to do with the presence of a request body. And that logic should probably live in Ember Promise.

**Comment by JarrodCTaylor** [comment]
While not the majority use case I agree there are scenarios where you could have a `POST` with no content. However, you had a test that is a `GET` with the `contentType` set to the non default value of `application/json` which is  superfluous, as `contentType` is for specifying the data type being sent to the server which of course is not happening in a `GET` request. I am working this morning on adding some logic for dealing with `contentType`. I will post additional information once I have something put together.

**Comment by benkiefer** [comment]
It isn't happening in that test's GET request, but it's perfectly legal to do a GET with a body.  It's also perfectly legal to specify a content type when there is no body. Nothing that was done in that test was against HTTP specification. It may not be the "best" thing, and may not fit in with REST, but there are a lot of arguments against REST, and not every request is suited to be REST-ful, (Login request for example).

I understand your concerns about semantics, but the goal of our PR was to make faujax more flexible when doing data comparisons, not make it the enforcer of REST. 

Thanks again for maintaining the library. We appreciate the work your are doing.

**Comment by benkiefer** [comment]
@williamsbdev I was just thinking that if I were sending XML (or some other more verbose message format) as the payload in a request I wouldn't expect the library to serialize my XML so that it could do comparison. 

I'm fine dropping this request. We should just make sure our stuff matches.

**Pull request closed without merging**
